# Generated by Django 4.1.6 on 2023-02-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_message_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_active_on_chat',
            field=models.BooleanField(default=False),
        ),
    ]
