# Generated by Django 4.1 on 2022-12-03 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0003_alter_task_done'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['done', 'created']},
        ),
    ]
