# Generated by Django 4.1 on 2022-12-03 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0004_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['done', '-created']},
        ),
    ]
