# Generated by Django 4.1.6 on 2023-02-04 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_tictactoegame_delete_tic_tac_toe_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tictactoegame',
            name='room',
        ),
    ]
