# Generated by Django 4.1.6 on 2023-02-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_tictactoegame_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='tictactoegame',
            name='room',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
