# Generated by Django 4.1.6 on 2023-02-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_alter_tictactoegame_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='tictactoegame',
            name='legal_moves',
            field=models.JSONField(default=list, max_length=9),
        ),
        migrations.AddField(
            model_name='tictactoegame',
            name='library_of_board',
            field=models.JSONField(default=dict, max_length=9),
        ),
        migrations.AddField(
            model_name='tictactoegame',
            name='mark',
            field=models.TextField(blank=True, default='O', max_length=1, null=True),
        ),
    ]
