# Generated by Django 4.1.6 on 2023-02-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_tictactoegame_legal_moves_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tictactoegame',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tictactoegame',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tictactoegame',
            name='outcome',
            field=models.CharField(default='false', max_length=10),
        ),
        migrations.AddField(
            model_name='tictactoegame',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tictactoegame',
            name='win',
            field=models.BooleanField(default=False),
        ),
    ]
