# Generated by Django 4.1.6 on 2023-02-09 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_tictactoegame_accepted_tictactoegame_canceled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tictactoegame',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='tictactoegame',
            name='canceled',
        ),
        migrations.RemoveField(
            model_name='tictactoegame',
            name='game_on',
        ),
        migrations.RemoveField(
            model_name='tictactoegame',
            name='outcome',
        ),
        migrations.RemoveField(
            model_name='tictactoegame',
            name='rejected',
        ),
        migrations.RemoveField(
            model_name='tictactoegame',
            name='win',
        ),
    ]
