# Generated by Django 4.1.6 on 2023-02-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_remove_tictactoegame_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tictactoegame',
            name='game_continue',
            field=models.IntegerField(default=0),
        ),
    ]
